Feature/ong1 100
alkemyTech/React-SXXI-T1 pull request #107
Opened 2022-12-01 18:54 UTC by cris-al

2022-12-02 02:43 UTC, rodrigotonso requested changes

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/Categories/CategoryHook/useCategory.js
> +                setLoading(false);
Pareciera que todos los caminos generan un setLoading(false), habría que borrarlos de los then ¿?

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/Categories/CategoryHook/useCategory.js
> +                setLoading(false);
Se que no es de tu tarea pero el código anterior esta algo complejo

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/News/Comment/Card/Card.jsx
> +            <CommentImg src={image !=='string' ? image : avatarUser} alt={'imagen'}/>
Es una validación rara, si envío un número ¿?
Siempre que podamos evitar lógica en la parte de los tags mejor, tal vez esta validación la podamos llevar afuera del return

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/News/Comment/Card/Card.jsx
> +                text?.text1 ?
text.text1? que sería ¿?

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/News/Comment/Card/Card.jsx
> +                    show ?  <CommentText>
De nuevo esta logica la podemos sacar afuera del return y tal vez queda más limpio esto por que podríamos evitar el condicional

2022-12-02 02:43 UTC, rodrigotonso commented on src/Components/views/News/Comment/hook/useComment.js
> +        }
lógica compleja, que buscamos lograr ¿?

2022-12-02 20:21 UTC, cris-al commented on src/Components/views/Categories/CategoryHook/useCategory.js
> +                setLoading(false);
Ya lo revise e hice los cambios

2022-12-02 20:21 UTC, cris-al commented on src/Components/views/News/Comment/Card/Card.jsx
> +            <CommentImg src={image !=='string' ? image : avatarUser} alt={'imagen'}/>
cambios realizados.

2022-12-02 20:34 UTC, cris-al commented on src/Components/views/News/Comment/Card/Card.jsx
> +                text?.text1 ?
La manera en que trabaje la parte de responsive al mostrar un texto largo fue usando una función que divide en dos al texto recibido (no necesariamente en partes iguales) ya sea el contenido de un comentario o la descripción de una novedad, esta función antes de dividir el texto verifica la longitud y el width del dispositivo y si cumple con las condiciones devuelve {text1, text2, points} si no cumple devuelve el texto recibido. La funcion se llama textDivider y esta en los customhooks de Comment y Detail.

2022-12-02 20:36 UTC, cris-al commented on src/Components/views/News/Comment/hook/useComment.js
> +        }
La respuesta esta dos comentarios arriba.

2022-12-02 20:36 UTC, cris-al commented on src/Components/views/News/Comment/Card/Card.jsx
> +                    show ?  <CommentText>
revisado y corregido.

2022-12-02 20:43 UTC, cris-al commented on src/Components/views/News/Comment/Card/Card.jsx
> +            <CommentImg src={image !=='string' ? image : avatarUser} alt={'imagen'}/>
la condicion de la imagen es porque lo que llega de la API en la propiedad image de los comentarios (no de todos) es "string" y no hablo del tipo de dato sino literalmente image: "string". Puede verlo en la imagen
![Captura de pantalla (18)](https://user-images.githubusercontent.com/102695487/205382489-10365a0e-216c-49f6-b95a-48c6fbd3cd80.png)

2022-12-05 12:29 UTC, rodrigotonso requested changes

2022-12-05 12:29 UTC, rodrigotonso commented on src/Components/views/News/Comment/hook/useComment.js
> +    if (text) {
Si no se recive un text se devuelve un undefined???
Si podemos evitar anidar if hagamoslo
En este caso te convendría arrancar con:

if(!text) return text
resto del código

2022-12-05 12:29 UTC, rodrigotonso commented on src/Components/views/Categories/CategoryHook/useCategory.js
> +  const { handleChange, handleSubmit, values, errors, handleBlur, touched, setFieldValue } = formik
Tengamos cuidado con el tema de los cambios por estilos de prettier, despues se vuelve muy dificil hacer el code review

2022-12-05 12:29 UTC, rodrigotonso commented on src/Components/views/News/Comment/hook/useComment.js
> +    else setMinSize(false)
no termino de entender por que encaramos la lógica asi ¿?

Los estados minSize, medSize y maxSize que harían ¿?
¿No podríamos usar un estado que sea commentSize (o algo así) que valga "min"||"med"||"max"???

2022-12-05 12:29 UTC, rodrigotonso commented on src/Components/views/News/Detail/components/ContainerResponsive.jsx
> +                                      <Paragraph dangerouslySetInnerHTML={{__html: text.text1 + text.text2}}/>
Hubo que hacer un inner???

Lo que se muestra en true y false es casi lo mismo podríamos abreviar

2022-12-05 20:38 UTC, cris-al commented on src/Components/views/News/Comment/hook/useComment.js
> +    if (text) {
Revisado y modificado. Ahora textDivider si recibe un texto null o undefined devuelve un string vacío y si no cumple con ninguna de las demás condiciones devuelve el mismo texto que llega. (modificado en la función textDivider de los archivos useComment.js y useDetailNews.js)

2022-12-05 20:54 UTC, cris-al commented on src/Components/views/News/Comment/hook/useComment.js
> +    else setMinSize(false)
La función handleResize la uso para saber el ancho del dispositivo. Los estados los uso para saber si dividir el texto en dos de un comentario o la descripción de una novedad. Por ejemplo si estoy en un dispositivo de menos de 490px de ancho (seteo el estado minSize en true) y el texto de un comentario tiene mas de 55 caracteres con textDivider hago un slice del texto y lo devuelvo dividido en dos solo para no mostrar un texto largo (muestro la primera parte concatenada con la constante points="...") y si se quiere ver el texto completo hay un botón que esconde o muestra la otra parte del texto. He considerado la sugerencia de hacer un solo estado (commentSize) y la he implementado tanto para useComment.js como para useDetailNews.js

2022-12-05 20:55 UTC, cris-al commented on src/Components/views/News/Detail/components/ContainerResponsive.jsx
> +                                      <Paragraph dangerouslySetInnerHTML={{__html: text.text1 + text.text2}}/>
revisado y corregido.

2022-12-06 16:08 UTC, rodrigotonso approved these changes

2022-12-06 16:29 UTC, merged