Feature/ong1 48
alkemyTech/React-SXXI-T1 pull request #11
Opened 2022-10-31 13:33 UTC by LuisGerezM

Terminado componente para titulo. En la card de la tarea se menciona el tema de una imagen, que si no existe usar una por defecto, pero profe Andre dijo que la haga por el momento sin imagen y que iba a consultar ese tema.

2022-10-31 15:25 UTC, cris-al approved these changes

2022-10-31 18:51 UTC, pcuneo requested changes
Falta la configuración de la imagen de fondo y la imagen por defecto.

2022-10-31 18:51 UTC, pcuneo commented on src/Components/views/ContactUs/ContactUs.Styled.js
> +>>>>>>> c0b95c59590a2b232eaf19db09b7216497d45ff6
Quedo mal el merge

2022-10-31 20:09 UTC, LuisGerezM commented on src/Components/views/ContactUs/ContactUs.Styled.js
> +>>>>>>> c0b95c59590a2b232eaf19db09b7216497d45ff6
Si acabo de ver, pense que habia guardado el cambio pero no. Y con respecto a lo de la imagen de fondo,  profe Andre dijo que la haga por el momento sin imagen y que iba a consultar ese tema ya que en figma no hay algo similar, y no se entiende bien el punto.

2022-11-01 12:57 UTC, pcuneo approved these changes

2022-11-02 00:04 UTC, LuisGerezM commented
@pcuneo Profe, disculpe, cuando pueda agradecería que chequee los cambios y si está todo en orden, y la tarjetita -ong1-48- en hecho puedo mergear con dev para que mis compañeros lo usen al componente. Muchas gracias.

2022-11-02 10:35 UTC, pcuneo commented
Si esta aprobado el pr denle merge, y el jira lo actualizo después.

2022-11-02 11:56 UTC, merged