Feature/ong1 50
alkemyTech/React-SXXI-T1 pull request #14
Opened 2022-10-31 18:21 UTC by LuisGerezM

Terminado estilos y lógica del componente detale de actividad (con datos mockeados);
Agregue ruta dinámica para la misma, actividades/:id
Modifiqué los estilos del componente CustomLink, renderizado en el componente global LinkReactRouter

2022-10-31 19:32 UTC, pcuneo requested changes
Revisar el tema del spinner

2022-10-31 19:32 UTC, pcuneo commented on src/Components/views/Activities/Detail/Detail.jsx
> +
El SpinnerLoad no aparece centrado en la pantalla y por el ancho ó alto esta excediendo el box y hace que aparezca un scroll

2022-10-31 19:34 UTC, pcuneo requested changes

2022-10-31 19:34 UTC, pcuneo commented on src/Components/views/Activities/Detail/hooks/useDetail.js
> +
Al correr la app hay un warning:

`React Hook useEffect has a missing dependency: 'idDetail'.`

Por como esta armado tiene sentido que si cambia el idDetail, se vuelva a ejecutar el useEffect

2022-10-31 20:44 UTC, LuisGerezM commented on src/Components/views/Activities/Detail/hooks/useDetail.js
> +
Una consulta profe, en este caso, si ya corregí las observaciones, debería cerrar esta pr y crear una nueva con los cambios realizados? o usar el --amend --no-edit?

2022-11-01 12:38 UTC, pcuneo approved these changes

2022-11-01 13:44 UTC, merged