Feature/ong1 28
alkemyTech/React-SXXI-T1 pull request #17
Opened 2022-11-01 14:25 UTC by cris-al

2022-11-02 10:58 UTC, pcuneo requested changes
Falta la parte de hacer el post o patch al servicio para crear/editar categorias 

https://ongapi.alkemy.org/api/docs#/Category

2022-11-02 10:58 UTC, pcuneo commented on src/Components/views/Categories/CategoriesForm.jsx
> +                        className={errors.image ? 'border-danger' : ''}
Respecto de validar el tipo de archivo.
Hasta donde pude seguir el código accept no hace ninguna validación, y sería mas natural que se valide con formik.

2022-11-02 11:16 UTC, pcuneo requested changes
Hacer que los valores y los errores de CKEditorComponent sean manejados por formik

2022-11-02 11:16 UTC, pcuneo commented on src/Components/GlobalComponents/CKEditor/CKEditorComponent.jsx
> +                    setDescError(()=>{ if(data==='') return 'Campo obligatorio'});
La validación debería realizarse con formik

2022-11-02 11:16 UTC, pcuneo commented on src/Components/views/Categories/CategoriesForm.jsx
> +    const [descError, setDescError] = useState('');
El error y el valor deberian ser manejados por formik

2022-11-02 11:24 UTC, pcuneo requested changes

2022-11-02 11:24 UTC, pcuneo commented on src/Components/GlobalComponents/CKEditor/CKEditorComponent.jsx
> +                    setDescError(()=>{ if(data==='') return 'Campo obligatorio'});
Para mostrar un sugerencia de como completar el campo deberían utilizar un `placeholder` y no `data`. De otra forma puede llevar al usuario a crear categorías con descripción "Descripción" por error.

2022-11-02 20:48 UTC, cris-al commented
@pcuneo correcciones terminadas.

2022-11-03 11:55 UTC, pcuneo requested changes

2022-11-03 11:55 UTC, pcuneo commented on src/Components/views/Categories/CategoriesForm.jsx
> +                    alert('Ha ocurrido un error...');
usar sweet alert.

2022-11-03 11:55 UTC, pcuneo commented on src/Components/views/Categories/CategoriesForm.jsx
> +                navigate('/backoffice/categories');
usar sweetalert

2022-11-03 11:55 UTC, pcuneo commented on src/Components/views/Categories/CategoriesForm.jsx
> +                .then(res => {
La url base de la api debería ser una configuración de ambiente, que salga del process.env.

Por otro lado al usar axios es mejor contruir un axios instance, para no tener que escribir la url completa cada vez.

https://axios-http.com/docs/instance

Por ejemplo:
// src/services/ONGAPI.js
const instance = axios.create({
  baseURL: 'https://ongapi.alkemy.org/api',
});

// src/Components/views/Categories/CategoriesForm.jsx
import ongapi from "src/services/ONGAPI"

ongapi.get(`/categories/${id}`)

2022-11-04 16:22 UTC, cris-al commented
sweetAlert y axios.create implementados @pcuneo

2022-11-04 19:37 UTC, pcuneo requested changes
La instancia de axios se crea una sola vez y se comparte en toda la app, la forma que esta implementada es creando una instancia por request que no  es la idea

2022-11-04 19:37 UTC, pcuneo commented on src/models/routes.js
>    CONTACTUS: "/contact-us",
creo que deberia ser como estaba antes

2022-11-04 19:37 UTC, pcuneo commented on src/Services/apiCall.service.js
>      });
La idea de la instancia era que se genera una sola vez y la usabas de la misma forma que axios.
En este caso estas creando una nueva instancia por cada llamada, que no es la idea.

2022-11-05 04:23 UTC, closed without merging