Feature/ong1 31
alkemyTech/React-SXXI-T1 pull request #18
Opened 2022-11-01 20:43 UTC by eugenia1984

Listo para el review.

Se puede ver en:
backoffice/create-testimonials
backoffice/edit-testimonials/id    (recibe por parametro un nro)

Deje comentado con axios para despues poder utilizarlo

2022-11-02 11:27 UTC, pcuneo requested changes
Falta integrar con la api https://ongapi.alkemy.org/api/docs#/Testimonial

2022-11-02 11:27 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/CKEditor/CKEditorComponent.jsx
> +                    setDescError(()=>{ if(data==='') return 'Campo obligatorio'});
La validación debería manejarse con formik

2022-11-02 11:27 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/TestimonialsForm.jsx
> +
Todos los campos deberían ser manejados por formik.

2022-11-02 11:30 UTC, pcuneo requested changes

2022-11-02 11:30 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/TestimonialsButtons.jsx
> +            text="Send" />
Poner el texto en español, ya que los usuarios son de habla hispana.

2022-11-03 00:48 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/CKEditor/CKEditorComponent.jsx
> +                    setDescError(()=>{ if(data==='') return 'Campo obligatorio'});
Integrado con "https://ongapi.alkemy.org/api/testimonials"

2022-11-03 00:52 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/TestimonialsButtons.jsx
> +            text="Send" />
Cambie el texto del boton a español

2022-11-03 00:53 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/CKEditor/CKEditorComponent.jsx
> +                data={ id ? "<p>Esta es la descripcion del testimonio</p>" : "<p>Descripción</p>"}
Cambiado:
 data={ testimonial.description ? testimonial.description : '' }

2022-11-03 00:59 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/TestimonialsForm.jsx
> +
Tengo:
const nameRegExp = /[a-z, A-Z]{4}/

export const validationSchema = Yup.object().shape({
  name : Yup.string()
    .matches(nameRegExp, validationMessages.name.format)
    .min(4, validationMessages.name.fieldLength)
    .required(validationMessages.name.required),
  image: Yup.mixed().required( validationMessages.image.required)
  .test( "fileFormat", "Solo formato .jpg y .png",
      value => value?.includes('.png'||'.jpg')
  ),
  description: Yup.string().required(validationMessages.description.required)
    .max(255, validationMessages.description.fieldLength)
});

2022-11-03 11:57 UTC, pcuneo requested changes

2022-11-03 11:57 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/hooks/useTestimonialsForms.js
> +          navigate('/backoffice/testimonials');
user sweetalert

2022-11-03 11:57 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/hooks/useTestimonialsForms.js
> +          navigate('/backoffice/testimonials');
usar sweet alert

2022-11-03 11:57 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/hooks/useTestimonialsForms.js
> +              .then(res => {
La url base de la api debería ser una configuración de ambiente, que salga del process.env.

Por otro lado al usar axios es mejor contruir un axios instance, para no tener que escribir la url completa cada vez.

https://axios-http.com/docs/instance

Por ejemplo:
// src/services/ONGAPI.js
const instance = axios.create({
baseURL: 'https://ongapi.alkemy.org/api',
});

// src/Components/views/Testimonials/useTertimonialsForm.jsx
import ongapi from "src/services/ONGAPI"

ongapi.get(/testimonials/${id})

2022-11-04 16:04 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/CKEditor/CKEditorComponent.jsx
> +                data={ id ? "<p>Esta es la descripcion del testimonio</p>" : "<p>Descripción</p>"}
@pcuneo recien termine de modificar todo, espero que este este ok, para poder ajustar los demas formularios guiandome con este

2022-11-04 19:28 UTC, pcuneo requested changes

2022-11-04 19:28 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Testimonials/TEstimonialsForms.jsx
> +import { useParams } from 'react-router-dom';
Hay un typo en el nombre del archivo

2022-11-07 14:24 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/TEstimonialsForms.jsx
> +import { useParams } from 'react-router-dom';
Ah, si corregí a TestimonialsForms.jsx

2022-11-07 14:28 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/hooks/useTestimonialsForms.js
> +              .then(res => {
En **Services/axiosService.js** tengo:

```JavaScript
import axios from "axios";

export const api = axios.create({
    baseURL: process.env.REACT_APP_BASE_URL
});`
```

Entonces en **Testmonials/useTestomonialsForms.js** ahora me importe:
```JavaScript
import { api } from 'Services/axiosService';
```

Y la uso:
```JavaScript
api.get(`testimonials/${id}`)
```

2022-11-07 14:30 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Testimonials/CKEditor/CKEditorComponent.jsx
> +                    setDescError(()=>{ if(data==='') return 'Campo obligatorio'});
Ahora esta con Formik y Yup

2022-11-08 01:04 UTC, pcuneo approved these changes

2022-11-08 12:26 UTC, merged