Feature/ong 29
alkemyTech/React-SXXI-T1 pull request #36
Opened 2022-11-10 18:15 UTC by eugenia1984

http://localhost:3000/backoffice/activities → Para crear una actividad
http://localhost:3000/backoffice/activities/:id → recibe como param un id que es un numero, para poder modificar la actividad, consulto aca:
https://ongapi.alkemy.org/api/activities

- arregle que la imagen llega bien
- y se ven los mensajes de error al crear una actividad

2022-11-10 23:50 UTC, pcuneo requested changes
Esta bastante bien, pero eviten user promises  explicitamente dentro de las funciones async.

2022-11-10 23:50 UTC, pcuneo commented on src/Components/views/Private/BackOffice/Acivities/hooks/useActivitiesForm.js
> +
En general sí estas dentro de una funcion async es preferible no usar promises explicitamente.
async/await siempre es mas legible y te permite hacer pull-up del código repetido.
Fijate que con async/await el código se puede leer de arriba a abajo en el órden de ejecución sin tener que entrar en callbacks anidados

```
  const onSubmit = async () => {
    const { name, description } = values;
    const body = { name, description, image: imageBase64 };
    const res = await Alert({
      icon: "warning",
      title: "¿Seguro/a?",
      cancelText: "Cancelar",
    });
    if (res.isConfirmed) {
      setLoading(true);
      try {
        if (id) {
          await api.put(`/activities/${id}`, {
            ...activity,
            ...body,
            image: imageBase64 || (await convertUrlToBase64(activity.image)),
          });
        } else {
          await api.post(`/activities`, body);
        }
        await Alert({ icon: "success", title: "Operación éxitosa" });
        navigate(backURL);
      } catch (err) {
        await Alert({ icon: "error", title: "Ha ocurrido un error" });
      } finally {
        setLoading(false);
      }
    }
  };
  ```

2022-11-11 14:19 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Acivities/hooks/useActivitiesForm.js
> +
deje todo con async await sin .then()

2022-11-11 17:58 UTC, pcuneo approved these changes

2022-11-11 18:31 UTC, merged