Feature/ONG1-125
alkemyTech/React-SXXI-T1 pull request #48
Opened 2022-11-14 22:22 UTC by LuisGerezM

Terminada feature ONG1-125. Tengo una consulta, la tarjeta dice "Deberá contener 3 columnas: La primera mostrará el logo y nombre de ONG, la segunda los ítems de navegación y la tercera los links a redes sociales de la ONG". Pero anteriormente dice que tengo que usar los datos obtenidos de la API, y la imagen que me trae no es de la ONG.
Por otro lado, destaca que tiene que ser 3 columnas, pero se olvidaron del newsLetter, por tanto, me pareció que quedaría mejor como lo hice ... Pero ud me dice, si tengo que cambiarlo (ajustandome 100% a la tarjeta de la actividad) o lo dejamos ahi (que es lo que me parece mejor).

2022-11-15 03:08 UTC, pcuneo requested changes

2022-11-15 03:08 UTC, pcuneo commented on src/utilities/navitems/navItems.util.js
> +];
La página de contribuye creo que tambien se puede agregar

2022-11-15 03:11 UTC, pcuneo requested changes
Revisar newsletter y que otras paginas se pueden agregar

2022-11-15 03:19 UTC, pcuneo commented
Me parece bien los cambios en el formato

2022-11-15 14:44 UTC, LuisGerezM commented on src/utilities/navitems/navItems.util.js
> +];
La página de contribuye es la de donación? porque en el figma sale un formulario en esa view. Pero si es la de donación le agrego ahora.

2022-11-16 20:24 UTC, pcuneo commented on src/utilities/navitems/navItems.util.js
> +];
si esa

2022-11-16 20:25 UTC, pcuneo approved these changes

2022-11-18 02:37 UTC, merged