Feature/ONG1 124
alkemyTech/React-SXXI-T1 pull request #51
Opened 2022-11-16 02:57 UTC by LuisGerezM

Primera entrega de lo realizado para la navegación del Header.

2022-11-16 20:39 UTC, pcuneo requested changes

2022-11-16 20:39 UTC, pcuneo commented on src/utilities/navitems/navItems.util.js
> +  { text: "Contacto", to: routes.CONTACT },
Por que "/about" y "/testimonios" no son constantes?

2022-11-16 20:56 UTC, LuisGerezM commented on src/utilities/navitems/navItems.util.js
> +  { text: "Contacto", to: routes.CONTACT },
Hola profe, porque aún no existen. Cuándo existan habrías que cambiarle ahi.

2022-11-16 22:46 UTC, LuisGerezM commented on src/utilities/navitems/navItems.util.js
> +  { text: "Contacto", to: routes.CONTACT },
Listo profe, agregadas ambas rutas

2022-11-18 00:52 UTC, pcuneo approved these changes

2022-11-18 02:52 UTC, merged