Feature/ong1 193
alkemyTech/React-SXXI-T1 pull request #54
Opened 2022-11-16 20:35 UTC by LuisGerezM

Creado componente reutilizable para listados

2022-11-16 21:05 UTC, pcuneo requested changes
Esta bien la tabla, pero el pr esta trayendo mas cosas que la tabla.
O incluir solo tabla  o espera a mergear el resto.

2022-11-16 21:13 UTC, LuisGerezM commented
@pcuneo En estos casos, como debería actuar? Ya que estoy trabajando con otras ramas, y a medida que voy haciendo pr voy cambiando, cada  vez que cambie a una nueva branch , si hago un pull con dev, seguiría teniendo lo que estaba haciendo en la branch que dejé en pr.

2022-11-18 00:54 UTC, pcuneo approved these changes

2022-11-18 01:31 UTC, LuisGerezM commented
@pcuneo Ahhh, si. Me colgué con eso. Muchas gracias profe.

2022-11-18 04:01 UTC, merged