Feature/ong1-64
alkemyTech/React-SXXI-T1 pull request #55
Opened 2022-11-16 20:40 UTC by LuisGerezM

Primera entrega actividad ONG1-64

2022-11-16 21:11 UTC, pcuneo requested changes
Esta bastante bien, falta el boton de crear slide.

2022-11-16 21:20 UTC, LuisGerezM commented
@pcuneo Cierto, ahora lo agrego

2022-11-16 21:34 UTC, LuisGerezM commented
@pcuneo Botón para crear slide agregado

2022-11-18 01:04 UTC, pcuneo approved these changes

2022-11-18 03:02 UTC, merged