Feature/ong1 65
alkemyTech/React-SXXI-T1 pull request #61
Opened 2022-11-18 18:49 UTC by eugenia1984

- En privateRoutes, que tenia:
USERSFORM: "users"  ---- que pasa a ---> USERSCREATE: "users/create"
USERSEDITFORM: "users/:id" ---- que pasa a ---> USERSEDITWITHID: "users/edit/:id

-Entonces las nuevas rutas privadas son:
USERS: "users"  ->  ver el listado desde bo
USERSCREATE: "users/create" → crear un usuario desde bo
USERSEDIT: "users/edit" → para usar con navigate(${privateRoutes.USEREDIT}/${id})
USERSEDITWITHID: "users/edit/:id" → editar un usuario desde bo

Listo para ver desde http://localhost:3000/backoffice/users

2022-11-19 02:43 UTC, pcuneo requested changes

2022-11-19 16:29 UTC, eugenia1984 commented on src/Components/views/Private/BackOffice/Users/UsersList.jsx
> +    navigate(`/${privateRoutes.BACKOFFICE}${privateRoutes.USERSEDIT}/:${id}`);
Buenas profe, si me confundi con la URL /users/edit/:id que recibe el id como parametro.

2022-11-21 23:19 UTC, pcuneo approved these changes

2022-11-21 23:19 UTC, pcuneo approved these changes

2022-11-22 18:45 UTC, merged