Feature/ONG1-195
alkemyTech/React-SXXI-T1 pull request #79
Opened 2022-11-23 19:03 UTC by LuisGerezM

- Modificado el color del boton editar del componente CustomTable
    - Corregida ubicación del botón volver del componente ActionSlides
    - Modificado componente Contribuye y Thanks
    - Modificado estilos componente CustomCards
    - Modificando el input file, cambiando estilos que vienen por defecto.
    - Solucionado BUG en input file cuando se edita una imagen, se arregló para que corrobore formato y tamaño si es que ingresa una nueva imagen.
    - Modificando cards del modal de orden de slides, agregandole hover.
    - Editada la barra de navegación cada vez que se activa.
    - Pasé a español el nombre de los campos en utilities/validationMessage.util.js
    
    AGREGADOS:
    - cambiando logo entre testimonios y novedades en Dashboard, para que quede acorde con el cambio que se hizo.
    - modificando carpeta public

2022-11-25 11:43 UTC, pcuneo requested changes

2022-11-25 11:43 UTC, pcuneo commented on src/App.js
> +import React from "react"
no esta bueno cambiar el formatter del código a mitad del proyecto.
esta todo el equipo de acuerdo con el cambio de formatter?

2022-11-25 11:57 UTC, LuisGerezM commented on src/App.js
> +import React from "react"
Buenos días profe, si, lo sé, es un tema que veníamos conversandolo a la ligera desde un principio, pero lo hablamos y estuvimos de acuerdo.

2022-11-26 13:10 UTC, pcuneo approved these changes
Obviamente no voy a revisar 1606 archivos. 
Ojo con el orden de merge.

Sean felices!

2022-11-26 16:24 UTC, merged