Feature/ong1 36
alkemyTech/React-SXXI-T1 pull request #8
Opened 2022-10-28 19:55 UTC by cris-al

2022-10-28 20:47 UTC, pcuneo requested changes

2022-10-28 20:47 UTC, pcuneo commented on src/Components/views/ContactUs/ContactUs.jsx
> +        phone: Yup.string().min(8,'Debe contener al menos 8 digitos')
Todo los campos deben ser requeridos.
No se esta validando requerido el teléfono.

2022-10-28 20:47 UTC, pcuneo commented on src/Components/views/ContactUs/ContactUs.jsx
> +                    backGround="succes"
verificar que "backGround" este escrito correctamente, arriba hay un cambio que   modifica la prop a "background"

2022-10-28 20:47 UTC, pcuneo commented on src/Components/views/ContactUs/ContactUs.jsx
> +                    backGround="succes"
"success" en ingles va con doble 's'

2022-10-28 20:47 UTC, pcuneo commented on src/Components/views/ContactUs/ContactUs.jsx
> +            <ButtonContact
Es confuso que el botón de contacto y el botón de ir al inicio sean  "ButtonContact".
El botón de volver al inicio va a cambiar en cada pantalla o va ser siempre el mismo?

2022-10-28 20:49 UTC, pcuneo commented
El requerimiento como esta en jira no pide la parte de "Quiero Contribuir". Y viendo las historias que vienen creo que tampoco va a existe la funcionalidad en esta pantalla. Recuerden que según enunciado el figma es un guía de estilo y no el requerimiento, el requerimiento es lo que esta en jira.

2022-10-28 21:15 UTC, cris-al commented on src/Components/views/ContactUs/ContactUs.jsx
> +        phone: Yup.string().min(8,'Debe contener al menos 8 digitos')
Corregido.

2022-10-28 21:15 UTC, cris-al commented on src/Components/views/ContactUs/ContactUs.jsx
> +                    backGround="succes"
corregido

2022-10-28 21:15 UTC, cris-al commented on src/Components/views/ContactUs/ContactUs.jsx
> +            <ButtonContact
Corregido.

2022-10-28 21:18 UTC, cris-al commented on src/Components/views/ContactUs/ContactUs.jsx
> +            <ButtonContact
El boton volver al inicio sera el mismo.

2022-10-29 15:01 UTC, pcuneo approved these changes

2022-10-29 15:02 UTC, pcuneo commented
@LuisGerezM Estas como segundo reviewer. Por mi esta listo este pr cuando aprobalo y dale merge.

2022-10-30 11:59 UTC, LuisGerezM commented
@pcuneo Perfecto, aprobando y mergeando el pr.

2022-10-30 12:00 UTC, LuisGerezM approved these changes

2022-10-30 12:02 UTC, merged