Feature/ong1 93
alkemyTech/React-SXXI-T1 pull request #82
Opened 2022-11-25 18:02 UTC by eugenia1984

- Utilizo la carpeta **Loading** de *GlobalComponents* (donde anteriormente deje el spinner que ya teníamos armado con css para mostrar al usuario la carga de información) para agregarle los Skeleton para dar visualización en el backOffice de que los datos se están cargando.

- Agrego el componente **SpinnerGrow** para utilizar como spinner en el BackOffice, lo reemplazo en la **CustomTable** que tenemos para armar todos los listados que se ven desde el Dashboard y lo documento en el README. Al ver el listado de los Slides se puede ver este spinner (El reruteo de Volver a DashBoard esta como http://localhost:3000/backoffice/dashboard y lo cambiamos a http://localhost:3000/backoffice) pero este ajuste esta junto al PR del feature/ONG1-93, cuando este aprobado corregimos todos los links de los botones del dashboard y del listado

- Creo los componentes **ButtonLoader** y **TextLoader** para que tanto el texto como el botón tengan una animación de carga del lado del backoffice mientras se está buscando la información a mostrar, lo documento en el readme.

2022-11-26 13:25 UTC, pcuneo requested changes

2022-11-26 13:25 UTC, pcuneo commented on src/Components/GlobalComponents/CustomTable/components/PersonalTableData/PersonalTableData.jsx
> +  const showLoad = () => <SpinnerGrow animation="grow" variant="primary" />;
según el readme este componente no maneja animation="grow"

2022-11-26 14:03 UTC, eugenia1984 commented on src/Components/GlobalComponents/CustomTable/components/PersonalTableData/PersonalTableData.jsx
> +  const showLoad = () => <SpinnerGrow animation="grow" variant="primary" />;
Buenas, lo que me quede pensando es que tal vez deberia cambiar el nombre del componente, trate de que sea lo más flexible posible, por eso le fui pasando como props casi todas las variables que nos brinda React-Bootrstrap.
Este es el spinner que vamos a usar en el BackOffice, en la documentación puse como la tabla de React-Bootstrap:
![image](https://user-images.githubusercontent.com/72580574/204092630-9b770fda-95f7-44dc-b9d6-9637ae55056f.png)
Es decir que puede ser el spinner que es el punto que va creciendo como el spinner que va girando, que se ve solo el borde.
¿Queres que agregue imagenes?
Le deje el link a la documentación de React-Bootrstrap, pense con eso estaba completo.?

2022-11-28 00:13 UTC, pcuneo approved these changes

2022-11-28 00:13 UTC, pcuneo commented on src/Components/GlobalComponents/CustomTable/components/PersonalTableData/PersonalTableData.jsx
> +  const showLoad = () => <SpinnerGrow animation="grow" variant="primary" />;
ok

2022-11-28 16:53 UTC, merged